name: Build and Publish Release

on:
  push:
    branches:
      - main
    # Trigger only if commit message starts with "publish:"
    # Use a filter on the commit message
    # We’ll use a conditional job instead

jobs:
  build-and-release:
    if: startsWith(github.event.head_commit.message, 'publish:')
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    name: Build & Release on ${{ matrix.os }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Read version
        id: read_version
        run: |
          echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV

      - name: Build executable (Windows or Linux)
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            pyinstaller --onefile --icon=./guibase/logo.ico main.py
            mv dist/main dist/PulsarAnalyticsKit-${VERSION}.AppImage
          else
            pyinstaller --onefile --icon=./guibase/logo.ico main.py
            mv dist/main.exe dist/PulsarAnalyticsKit-${VERSION}.exe
          fi
        shell: bash

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: v${{ env.VERSION }}
          files: |
            dist/PulsarAnalyticsKit-${{ env.VERSION }}.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
