on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    if: startsWith(github.event.head_commit.message, 'publish:')
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: Build & Release on ${{ matrix.os }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Read version
        id: read_version
        run: echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV

      - name: Install appimagetool (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libfuse2
          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          mv appimagetool-x86_64.AppImage appimagetool

          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy-x86_64.AppImage
          mv linuxdeploy-x86_64.AppImage linuxdeploy

      - name: Build executable
        run: |
          pyinstaller --noconfirm --clean ./mainbuild.spec
        shell: bash

      - name: Build AppImage (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: |

          mkdir -p AppDir/usr/bin
          cp dist/PulsarAnalyticsKit-${{ env.VERSION }}-linux AppDir/usr/bin/PulsarAnalyticsKit
          chmod +x AppDir/usr/bin/PulsarAnalyticsKit
          mkdir -p AppDir/usr/share/icons/hicolor/256x256/apps
          cp ./guibase/logo.png AppDir/usr/share/icons/hicolor/256x256/apps/pulsar.png
          mkdir -p AppDir/usr/share/applications

          echo "[Desktop Entry]
          Version=1.0
          X-AppVersion=${{ env.VERSION }}
          Name=Pulsar Analytics Kit
          Exec=PulsarAnalyticsKit
          Icon=pulsar
          Type=Application
          Categories=Science;" > AppDir/usr/share/applications/pulsar.desktop

          ln -s AppDir/usr/share/applications/pulsar.desktop AppDir/pulsar.desktop
          ln -s AppDir/usr/share/icons/hicolor/256x256/apps/pulsar.png / AppDir/pulsar.png
          chmod 644 AppDir/usr/share/applications/pulsar.desktop

          ls -la
          echo "Building AppImage LinuxDeploy..."
          
          ./linuxdeploy-x86_64.AppImage -v1 \
              --appdir AppDir \
              --output appimage \
              --executable app \
              --desktop-file AppDir/pulsar.desktop \
              --icon-file AppDir/pulsar.png

          chmod +x appimagetool

          ./appimagetool AppDir "PulsarAnalyticsKit-${{ env.VERSION }}.AppImage"

          chmod +x appimagetool
          ./appimagetool AppDir "PulsarAnalyticsKit-${{ env.VERSION }}.AppImage"

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: v${{ env.VERSION }}
          files: |
            dist/PulsarAnalyticsKit-${{ env.VERSION }}-win.exe
            PulsarAnalyticsKit-${{ env.VERSION }}.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}